// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VnfmServiceClient is the client API for VnfmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VnfmServiceClient interface {
	// StartLocalVim starts a Virtualized Infrastructure Manager on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the vnfm/config.yaml
	//   3. all bytes constituting the Virtualized Infrastructure Manager YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalVim(ctx context.Context, opts ...grpc.CallOption) (VnfmService_StartLocalVimClient, error)
	// StartFromPreviousVim starts a new Virtualized Infrastructure Manager based on a previous one.
	// If the previous Virtualized Infrastructure Manager does not have the can-replay condition set this call will result in an error.
	StartFromPreviousVim(ctx context.Context, in *StartFromPreviousVimRequest, opts ...grpc.CallOption) (*StartVimResponse, error)
	// StartVimRequest starts a new Virtualized Infrastructure Manager based on its specification.
	StartVim(ctx context.Context, in *StartVimRequest, opts ...grpc.CallOption) (*StartVimResponse, error)
	// Searches for Virtualized Infrastructure Manager(s) known to this instance
	ListVims(ctx context.Context, in *ListVimsRequest, opts ...grpc.CallOption) (*ListVimsResponse, error)
	// Subscribe listens to new Virtualized Infrastructure Manager(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (VnfmService_SubscribeClient, error)
	// GetVim retrieves details of a single Virtualized Infrastructure Manager
	GetVim(ctx context.Context, in *GetVimRequest, opts ...grpc.CallOption) (*GetVimResponse, error)
	// Listen listens to Virtualized Infrastructure Manager updates and log output of a running Virtualized Infrastructure Manager
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (VnfmService_ListenClient, error)
	// StopVim stops a currently running Virtualized Infrastructure Manager
	StopVim(ctx context.Context, in *StopVimRequest, opts ...grpc.CallOption) (*StopVimResponse, error)
}

type vnfmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVnfmServiceClient(cc grpc.ClientConnInterface) VnfmServiceClient {
	return &vnfmServiceClient{cc}
}

func (c *vnfmServiceClient) StartLocalVim(ctx context.Context, opts ...grpc.CallOption) (VnfmService_StartLocalVimClient, error) {
	stream, err := c.cc.NewStream(ctx, &VnfmService_ServiceDesc.Streams[0], "/v1.VnfmService/StartLocalVim", opts...)
	if err != nil {
		return nil, err
	}
	x := &vnfmServiceStartLocalVimClient{stream}
	return x, nil
}

type VnfmService_StartLocalVimClient interface {
	Send(*StartLocalVimRequest) error
	CloseAndRecv() (*StartVimResponse, error)
	grpc.ClientStream
}

type vnfmServiceStartLocalVimClient struct {
	grpc.ClientStream
}

func (x *vnfmServiceStartLocalVimClient) Send(m *StartLocalVimRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vnfmServiceStartLocalVimClient) CloseAndRecv() (*StartVimResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartVimResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vnfmServiceClient) StartFromPreviousVim(ctx context.Context, in *StartFromPreviousVimRequest, opts ...grpc.CallOption) (*StartVimResponse, error) {
	out := new(StartVimResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfmService/StartFromPreviousVim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vnfmServiceClient) StartVim(ctx context.Context, in *StartVimRequest, opts ...grpc.CallOption) (*StartVimResponse, error) {
	out := new(StartVimResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfmService/StartVim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vnfmServiceClient) ListVims(ctx context.Context, in *ListVimsRequest, opts ...grpc.CallOption) (*ListVimsResponse, error) {
	out := new(ListVimsResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfmService/ListVims", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vnfmServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (VnfmService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &VnfmService_ServiceDesc.Streams[1], "/v1.VnfmService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &vnfmServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VnfmService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type vnfmServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *vnfmServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vnfmServiceClient) GetVim(ctx context.Context, in *GetVimRequest, opts ...grpc.CallOption) (*GetVimResponse, error) {
	out := new(GetVimResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfmService/GetVim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vnfmServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (VnfmService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &VnfmService_ServiceDesc.Streams[2], "/v1.VnfmService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &vnfmServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VnfmService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type vnfmServiceListenClient struct {
	grpc.ClientStream
}

func (x *vnfmServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vnfmServiceClient) StopVim(ctx context.Context, in *StopVimRequest, opts ...grpc.CallOption) (*StopVimResponse, error) {
	out := new(StopVimResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfmService/StopVim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VnfmServiceServer is the server API for VnfmService service.
// All implementations must embed UnimplementedVnfmServiceServer
// for forward compatibility
type VnfmServiceServer interface {
	// StartLocalVim starts a Virtualized Infrastructure Manager on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the vnfm/config.yaml
	//   3. all bytes constituting the Virtualized Infrastructure Manager YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalVim(VnfmService_StartLocalVimServer) error
	// StartFromPreviousVim starts a new Virtualized Infrastructure Manager based on a previous one.
	// If the previous Virtualized Infrastructure Manager does not have the can-replay condition set this call will result in an error.
	StartFromPreviousVim(context.Context, *StartFromPreviousVimRequest) (*StartVimResponse, error)
	// StartVimRequest starts a new Virtualized Infrastructure Manager based on its specification.
	StartVim(context.Context, *StartVimRequest) (*StartVimResponse, error)
	// Searches for Virtualized Infrastructure Manager(s) known to this instance
	ListVims(context.Context, *ListVimsRequest) (*ListVimsResponse, error)
	// Subscribe listens to new Virtualized Infrastructure Manager(s) updates
	Subscribe(*SubscribeRequest, VnfmService_SubscribeServer) error
	// GetVim retrieves details of a single Virtualized Infrastructure Manager
	GetVim(context.Context, *GetVimRequest) (*GetVimResponse, error)
	// Listen listens to Virtualized Infrastructure Manager updates and log output of a running Virtualized Infrastructure Manager
	Listen(*ListenRequest, VnfmService_ListenServer) error
	// StopVim stops a currently running Virtualized Infrastructure Manager
	StopVim(context.Context, *StopVimRequest) (*StopVimResponse, error)
	mustEmbedUnimplementedVnfmServiceServer()
}

// UnimplementedVnfmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVnfmServiceServer struct {
}

func (UnimplementedVnfmServiceServer) StartLocalVim(VnfmService_StartLocalVimServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalVim not implemented")
}
func (UnimplementedVnfmServiceServer) StartFromPreviousVim(context.Context, *StartFromPreviousVimRequest) (*StartVimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousVim not implemented")
}
func (UnimplementedVnfmServiceServer) StartVim(context.Context, *StartVimRequest) (*StartVimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVim not implemented")
}
func (UnimplementedVnfmServiceServer) ListVims(context.Context, *ListVimsRequest) (*ListVimsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVims not implemented")
}
func (UnimplementedVnfmServiceServer) Subscribe(*SubscribeRequest, VnfmService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedVnfmServiceServer) GetVim(context.Context, *GetVimRequest) (*GetVimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVim not implemented")
}
func (UnimplementedVnfmServiceServer) Listen(*ListenRequest, VnfmService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedVnfmServiceServer) StopVim(context.Context, *StopVimRequest) (*StopVimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVim not implemented")
}
func (UnimplementedVnfmServiceServer) mustEmbedUnimplementedVnfmServiceServer() {}

// UnsafeVnfmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VnfmServiceServer will
// result in compilation errors.
type UnsafeVnfmServiceServer interface {
	mustEmbedUnimplementedVnfmServiceServer()
}

func RegisterVnfmServiceServer(s grpc.ServiceRegistrar, srv VnfmServiceServer) {
	s.RegisterService(&VnfmService_ServiceDesc, srv)
}

func _VnfmService_StartLocalVim_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VnfmServiceServer).StartLocalVim(&vnfmServiceStartLocalVimServer{stream})
}

type VnfmService_StartLocalVimServer interface {
	SendAndClose(*StartVimResponse) error
	Recv() (*StartLocalVimRequest, error)
	grpc.ServerStream
}

type vnfmServiceStartLocalVimServer struct {
	grpc.ServerStream
}

func (x *vnfmServiceStartLocalVimServer) SendAndClose(m *StartVimResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vnfmServiceStartLocalVimServer) Recv() (*StartLocalVimRequest, error) {
	m := new(StartLocalVimRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VnfmService_StartFromPreviousVim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousVimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfmServiceServer).StartFromPreviousVim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfmService/StartFromPreviousVim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfmServiceServer).StartFromPreviousVim(ctx, req.(*StartFromPreviousVimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VnfmService_StartVim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfmServiceServer).StartVim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfmService/StartVim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfmServiceServer).StartVim(ctx, req.(*StartVimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VnfmService_ListVims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfmServiceServer).ListVims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfmService/ListVims",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfmServiceServer).ListVims(ctx, req.(*ListVimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VnfmService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VnfmServiceServer).Subscribe(m, &vnfmServiceSubscribeServer{stream})
}

type VnfmService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type vnfmServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *vnfmServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VnfmService_GetVim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfmServiceServer).GetVim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfmService/GetVim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfmServiceServer).GetVim(ctx, req.(*GetVimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VnfmService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VnfmServiceServer).Listen(m, &vnfmServiceListenServer{stream})
}

type VnfmService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type vnfmServiceListenServer struct {
	grpc.ServerStream
}

func (x *vnfmServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VnfmService_StopVim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfmServiceServer).StopVim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfmService/StopVim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfmServiceServer).StopVim(ctx, req.(*StopVimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VnfmService_ServiceDesc is the grpc.ServiceDesc for VnfmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VnfmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VnfmService",
	HandlerType: (*VnfmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousVim",
			Handler:    _VnfmService_StartFromPreviousVim_Handler,
		},
		{
			MethodName: "StartVim",
			Handler:    _VnfmService_StartVim_Handler,
		},
		{
			MethodName: "ListVims",
			Handler:    _VnfmService_ListVims_Handler,
		},
		{
			MethodName: "GetVim",
			Handler:    _VnfmService_GetVim_Handler,
		},
		{
			MethodName: "StopVim",
			Handler:    _VnfmService_StopVim_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalVim",
			Handler:       _VnfmService_StartLocalVim_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _VnfmService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _VnfmService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vnfm.proto",
}
